http:
  routers:
    # HTTPS router
    ssr-router:
      rule: "Host(`session-one.duckdns.org`)"
      service: "ssr-service"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - "security-headers"
      priority: 100

    dashboard-secure:
      rule: "Host(`session-one.duckdns.org`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      service: api@internal
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - dashboard-auth
      priority: 1
